# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    admin.categoria:
        class: App\Admin\CategoriaAdmin
        arguments: [~, App\Entity\Categoria, App\Controller\CategoriaAdminController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Categoria }
        public: true

    admin.cliente:
        class: App\Admin\ClienteAdmin
        arguments: [~, App\Entity\Cliente, App\Controller\ClienteAdminController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Cliente }
        public: true

    admin.compra:
        class: App\Admin\CompraAdmin
        arguments: [~, App\Entity\Compra, App\Controller\CompraAdminController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Compra }
        public: true

    admin.produto:
        class: App\Admin\ProdutoAdmin
        arguments: [~, App\Entity\Produto, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Produto }
        public: true

    admin.endereco:
        class: App\Admin\EnderecoAdmin
        arguments: [~, App\Entity\Endereco, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Endereco }
        public: true

    admin.estado:
        class: App\Admin\EstadoAdmin
        arguments: [~, App\Entity\Estado, App\Controller\EstadoAdminController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Estado }
        public: true

    admin.pedido:
        class: App\Admin\PedidoAdmin
        arguments: [~, App\Entity\Pedido, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Pedido }
        public: true
